import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {loadEnvFile} from 'node:process';
try{loadEnvFile(new URL('../back/.env',import.meta.url));}catch{/* Variables del entorno tienen prioridad. */}
const url=process.env.TEST_API_URL||'http://127.0.0.1:4000/graphql';
async function gql(query,variables={},options={}){const headers={'Content-Type':'application/json',...(options.admin?{'x-admin-key':process.env.ADMIN_KEY}:{}),...(options.token?{Authorization:`Bearer ${options.token}`}:{}),...(options.authBridge?{'x-auth-bridge-secret':process.env.AUTH_BRIDGE_SECRET}:{})};const res=await fetch(url,{method:'POST',headers,body:JSON.stringify({query,variables})});const body=await res.json();if(body.errors)throw new Error(body.errors[0].message);return body.data;}
const {categorias}=await gql('{categorias{id nombre productos{id categoria{id}}}}');assert(categorias.length>=4);
assert.ok(process.env.AUTH_BRIDGE_SECRET,'Define AUTH_BRIDGE_SECRET en back/.env para probar autenticación.');
const correo=`api-${randomUUID()}@example.test`;const password='PruebaSegura-123';
const registrar='mutation($datos:RegistroInput!){registrarUsuario(datos:$datos){token usuario{id nombre email rol}}}';
const credenciales={nombre:'Cliente de API',email:correo,password};
await assert.rejects(()=>gql(registrar,{datos:credenciales}),/servidor web/);
const {registrarUsuario:sesion}=await gql(registrar,{datos:credenciales},{authBridge:true});
assert.equal(sesion.usuario.email,correo);assert.match(sesion.token,/^[^.]+\.[^.]+\.[^.]+$/);
const auth={token:sesion.token};
const iniciar='mutation($datos:CredencialesInput!){iniciarSesion(datos:$datos){token usuario{id email}}}';
const {iniciarSesion:sesionLogin}=await gql(iniciar,{datos:{email:correo,password}},{authBridge:true});
assert.equal(sesionLogin.usuario.id,sesion.usuario.id);
await assert.rejects(()=>gql(iniciar,{datos:{email:correo,password:'incorrecta'}},{authBridge:true}),/incorrectos/);
const {usuarioActual}=await gql('{usuarioActual{id nombre email rol}}',{},auth);assert.equal(usuarioActual.id,sesion.usuario.id);
const correoOtro=`api-${randomUUID()}@example.test`;
const {registrarUsuario:otraSesion}=await gql(registrar,{datos:{nombre:'Otra cuenta API',email:correoOtro,password}},{authBridge:true});
const otraAuth={token:otraSesion.token};
const datos={nombre:'PRUEBA API - artículo temporal',descripcion:'Artículo creado por la prueba automática.',precio:19.9,imagen:'/images/keyboard.jpg',stock:3,marca:'TEST',especificaciones:'Solo pruebas',categoriaId:categorias[0].id};
const crear='mutation($datos:ProductoInput!){crearProducto(datos:$datos){id stock precio}}';
await assert.rejects(()=>gql(crear,{datos}),/administración/);
const {crearProducto:producto}=await gql(crear,{datos},{admin:true});const id=producto.id;
const leer=async()=> (await gql('query($id:Int!){producto(id:$id){stock precio nombre}}',{id})).producto;
const comprar='mutation($datos:PedidoInput!){crearPedido(datos:$datos){id total detalles{nombreProducto precioUnitario cantidad producto{id}}}}';
const pedido=cantidad=>({nombre:'Cliente de prueba',email:'prueba@example.test',direccion:'Calle de prueba 123, Guadalajara, 44100',claveSolicitud:randomUUID(),renglones:[{productoId:id,cantidad}]});
await assert.rejects(()=>gql(comprar,{datos:pedido(1)}),/Inicia sesión/);
await assert.rejects(()=>gql('{pedidos{id}}'),/Inicia sesión/);
await assert.rejects(()=>gql(comprar,{datos:pedido(0)},auth),/cantidades/);assert.equal((await leer()).stock,3);
const inexistente={...pedido(1),renglones:[{productoId:id,cantidad:1},{productoId:2147483647,cantidad:1}]};
await assert.rejects(()=>gql(comprar,{datos:inexistente},auth),/stock/);assert.equal((await leer()).stock,3,'La transacción debe revertir el primer descuento.');
const datosPedido=pedido(2);const {crearPedido:primero}=await gql(comprar,{datos:datosPedido},auth);assert.equal(primero.total,39.8);assert.equal((await leer()).stock,1);
const repetido=await gql(comprar,{datos:datosPedido},auth);assert.equal(repetido.crearPedido.id,primero.id);assert.equal((await leer()).stock,1);
await assert.rejects(()=>gql(comprar,{datos:{...datosPedido,nombre:'Otra persona'}},auth),/otros datos/);
const resultados=await Promise.allSettled([gql(comprar,{datos:pedido(1)},auth),gql(comprar,{datos:pedido(1)},auth)]);assert.equal(resultados.filter(r=>r.status==='fulfilled').length,1,'Solo una compra puede consumir la última unidad.');assert.equal((await leer()).stock,0);
await gql('mutation($id:Int!,$datos:ProductoInput!){actualizarProducto(id:$id,datos:$datos){id}}',{id,datos:{...datos,nombre:'PRUEBA API editada',precio:25.5,stock:0}},{admin:true});assert.equal((await leer()).precio,25.5);
await gql('mutation($id:Int!){eliminarProducto(id:$id)}',{id},{admin:true});await assert.rejects(leer,/disponible/);
const {pedidos}=await gql('{pedidos{id total detalles{nombreProducto precioUnitario producto{id}}}}',{},auth);const guardado=pedidos.find(p=>p.id===primero.id);assert.equal(guardado.total,39.8);assert.equal(guardado.detalles[0].precioUnitario,19.9);assert.equal(guardado.detalles[0].nombreProducto,datos.nombre);
assert.equal((await gql('{pedidos{id}}',{},otraAuth)).pedidos.length,0,'Una cuenta no debe ver los pedidos de otra.');
const {productos}=await gql('{productos(limite:1,desde:1){total items{id}}}');assert.equal(productos.items.length,1);
await assert.rejects(()=>gql('{productos(limite:101){total}}'),/Paginación/);
console.log('OK: registro, login, token Bearer, acceso protegido, pedidos por usuario, relaciones, paginación, acceso admin, CRUD, rollback, idempotencia, última unidad e historial de precios.');
console.log('La prueba deja dos pedidos de TEST y un producto TEST dado de baja para conservar las relaciones.');
