import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {loadEnvFile} from 'node:process';
try{loadEnvFile(new URL('../back/.env',import.meta.url));}catch{/* Variables del entorno tienen prioridad. */}
const url=process.env.TEST_API_URL||'http://127.0.0.1:4000/graphql';
async function gql(query,variables={},options={}){const headers={'Content-Type':'application/json',...(options.admin?{Authorization:`Bearer ${process.env.TEST_ADMIN_TOKEN||process.env.ADMIN_KEY}`}:{}) ,...(options.token?{Authorization:`Bearer ${options.token}`}:{}) ,...(options.authBridge?{'x-auth-bridge-secret':process.env.AUTH_BRIDGE_SECRET}:{})};const res=await fetch(url,{method:'POST',headers,body:JSON.stringify({query,variables})});const body=await res.json();if(body.errors)throw new Error(`${body.errors[0].message} [${query}]`);if(!body.data)throw new Error(`GraphQL returned no data [${query}]`);return body.data;}
const {categorias}=await gql('{categorias{id nombre productos{id categoria{id}}}}');assert(categorias.length>=4);
assert.ok(process.env.AUTH_BRIDGE_SECRET,'Define AUTH_BRIDGE_SECRET en back/.env para probar autenticación.');
const correo=`api-${randomUUID()}@example.test`;const password='PruebaSegura-123';
const registrar='mutation($datos:RegistroInput!){registrarUsuario(datos:$datos){token usuario{id nombre email rol}}}';
const credenciales={nombre:'Cliente de API',email:correo,password};
await assert.rejects(()=>gql(registrar,{datos:credenciales}),/servidor web/);
const {registrarUsuario:sesion}=await gql(registrar,{datos:credenciales},{authBridge:true});
assert.equal(sesion.usuario.email,correo);assert.match(sesion.token,/^[^.]+\.[^.]+\.[^.]+$/);
const auth={token:sesion.token};
const iniciar='mutation($datos:CredencialesInput!){iniciarSesion(datos:$datos){token usuario{id email rol}}}';
const {iniciarSesion:sesionLogin}=await gql(iniciar,{datos:{email:correo,password}},{authBridge:true});
assert.equal(sesionLogin.usuario.id,sesion.usuario.id);
await assert.rejects(()=>gql(iniciar,{datos:{email:correo,password:'incorrecta'}},{authBridge:true}),/incorrectos/);
const adminEmail=process.env.TEST_ADMIN_EMAIL||process.env.ADMIN_EMAIL;
const adminPassword=process.env.TEST_ADMIN_PASSWORD||process.env.ADMIN_PASSWORD;
assert.ok(adminEmail&&adminPassword,'Define ADMIN_EMAIL y ADMIN_PASSWORD (o TEST_ADMIN_EMAIL y TEST_ADMIN_PASSWORD) para probar el acceso administrativo.');
const {iniciarSesion:sesionAdmin}=await gql(iniciar,{datos:{email:adminEmail,password:adminPassword}},{authBridge:true});
assert.equal(sesionAdmin.usuario.rol,'ADMIN');process.env.TEST_ADMIN_TOKEN=sesionAdmin.token;
const {usuarioActual}=await gql('{usuarioActual{id nombre email rol}}',{},auth);assert.equal(usuarioActual.id,sesion.usuario.id);
const correoOtro=`api-${randomUUID()}@example.test`;
const {registrarUsuario:otraSesion}=await gql(registrar,{datos:{nombre:'Otra cuenta API',email:correoOtro,password}},{authBridge:true});
const otraAuth={token:otraSesion.token};
const datos={nombre:'PRUEBA API - artículo temporal',descripcion:'Artículo creado por la prueba automática.',precio:19.9,imagen:'/images/keyboard.jpg',stock:3,marca:'TEST',especificaciones:'Solo pruebas',categoriaId:categorias[0].id};
const crear='mutation($datos:ProductoInput!){crearProducto(datos:$datos){id stock precio}}';
await assert.rejects(()=>gql(crear,{datos}),/Inicia sesión/);
await assert.rejects(()=>gql(crear,{datos},{token:auth.token}),/permiso/);
const {crearProducto:producto}=await gql(crear,{datos},{admin:true});const id=producto.id;
const stockInicial=await gql('query($id:Int!){adminMovimientos(productoId:$id){items{tipo cantidad}}}',{id},{admin:true});assert.ok(stockInicial.adminMovimientos.items.some(m=>m.tipo==='INICIAL'&&m.cantidad===3));
const leer=async()=> (await gql('query($id:Int!){producto(id:$id){stock precio nombre}}',{id})).producto;
const comprar='mutation($datos:PedidoInput!){crearPedido(datos:$datos){id total detalles{nombreProducto precioUnitario cantidad producto{id}}}}';
const pedido=cantidad=>({nombre:'Cliente de prueba',email:'prueba@example.test',direccion:'Calle de prueba 123, Guadalajara, 44100',claveSolicitud:randomUUID(),renglones:[{productoId:id,cantidad}]});
await assert.rejects(()=>gql(comprar,{datos:pedido(1)}),/Inicia sesión/);
await assert.rejects(()=>gql('{pedidos{id}}'),/Inicia sesión/);
await assert.rejects(()=>gql(comprar,{datos:pedido(0)},auth),/cantidades/);assert.equal((await leer()).stock,3);
const inexistente={...pedido(1),renglones:[{productoId:id,cantidad:1},{productoId:2147483647,cantidad:1}]};
await assert.rejects(()=>gql(comprar,{datos:inexistente},auth),/stock/);assert.equal((await leer()).stock,3,'La transacción debe revertir el primer descuento.');
const datosPedido=pedido(2);const {crearPedido:primero}=await gql(comprar,{datos:datosPedido},auth);assert.equal(primero.total,39.8);assert.equal((await leer()).stock,1);
const repetido=await gql(comprar,{datos:datosPedido},auth);assert.equal(repetido.crearPedido.id,primero.id);assert.equal((await leer()).stock,1);
await assert.rejects(()=>gql(comprar,{datos:{...datosPedido,nombre:'Otra persona'}},auth),/otros datos/);
const resultados=await Promise.allSettled([gql(comprar,{datos:pedido(1)},auth),gql(comprar,{datos:pedido(1)},auth)]);assert.equal(resultados.filter(r=>r.status==='fulfilled').length,1,'Solo una compra puede consumir la última unidad.');assert.equal((await leer()).stock,0);
await gql('mutation($id:Int!,$datos:ProductoInput!){actualizarProducto(id:$id,datos:$datos){id}}',{id,datos:{...datos,nombre:'PRUEBA API editada',precio:25.5,stock:0}},{admin:true});assert.equal((await leer()).precio,25.5);
await assert.rejects(()=>gql('query{adminPedidos{total}}',{}, {token:auth.token}),/permiso/);
const fechaDesde=new Date(Date.now()-30*86400000).toISOString();const fechaHasta=new Date().toISOString();
const dashboard=await gql('query($desde:String!,$hasta:String!){adminDashboard(desde:$desde,hasta:$hasta){totalPedidos pedidosPendientes pedidosRecientes{id} ventasTotales stockBajo sinExistencias}}',{desde:fechaDesde,hasta:fechaHasta},{admin:true});assert.ok(dashboard.adminDashboard.totalPedidos>=2);assert.ok(dashboard.adminDashboard.pedidosPendientes>=2);assert.ok(dashboard.adminDashboard.pedidosRecientes.some(p=>p.id===primero.id),'El pedido nuevo debe aparecer en la actividad reciente del dashboard.');
await assert.rejects(()=>gql('mutation($id:Int!,$estado:EstadoPedido!){actualizarEstadoPedido(id:$id,estado:$estado){id}}',{id:primero.id,estado:'PAGADO'},{admin:true}),/No se permite/);
await gql('mutation($id:Int!,$estado:EstadoPedido!,$motivo:String){actualizarEstadoPedido(id:$id,estado:$estado,motivo:$motivo){id}}',{id:primero.id,estado:'CANCELADO',motivo:null},{admin:true});
assert.equal((await leer()).stock,2,'Cancelar el primer pedido debe liberar sus unidades una sola vez.');
await assert.rejects(()=>gql('mutation($id:Int!,$estado:EstadoPedido!){actualizarEstadoPedido(id:$id,estado:$estado){id}}',{id:primero.id,estado:'CANCELADO'},{admin:true}),/No se permite/);
await gql('mutation($id:Int!,$estado:EstadoPedido!){actualizarEstadoPedido(id:$id,estado:$estado){id}}',{id:resultados.find(r=>r.status==='fulfilled').value.crearPedido.id,estado:'CANCELADO'},{admin:true});
assert.equal((await leer()).stock,3,'Cancelar ambos pedidos debe restaurar exactamente el stock original.');
const ajustar='mutation($productoId:Int!,$cantidad:Int!,$tipo:TipoMovimientoInventario!,$motivo:String!){ajustarInventario(productoId:$productoId,cantidad:$cantidad,tipo:$tipo,motivo:$motivo){id stock}}';
assert.equal((await gql(ajustar,{productoId:id,cantidad:0,tipo:'AJUSTE',motivo:'Prueba de stock cero'},{admin:true})).ajustarInventario.stock,0);
assert.equal((await gql(ajustar,{productoId:id,cantidad:3,tipo:'ENTRADA',motivo:'Reposición de prueba'},{admin:true})).ajustarInventario.stock,3);
await assert.rejects(()=>gql(ajustar,{productoId:id,cantidad:4,tipo:'SALIDA',motivo:'Salida superior al stock'},{admin:true}),/supera las existencias/);
const historial=await gql('query($id:Int!){historialPedido(id:$id){hacia motivo actor{nombre}}}',{id:primero.id},{admin:true});assert.equal(historial.historialPedido[0].hacia,'CANCELADO');
const movimientos=await gql('query($id:Int!){adminMovimientos(productoId:$id){items{tipo cantidad motivo}}}',{id},{admin:true});assert.ok(movimientos.adminMovimientos.items.some(m=>m.tipo==='CANCELACION'&&m.cantidad===2));
const clientes=await gql('query($buscar:String!){adminClientes(buscar:$buscar){items{id nombre email totalPedidos gastoConfirmado}}}',{buscar:correo},{admin:true});assert.equal(clientes.adminClientes.items[0].email,correo);
const pagos=await gql('query{adminPagos{total items{id estado}}}',{}, {admin:true});assert.ok(pagos.adminPagos.total>=0);
const nombreCategoria=`Prueba ${randomUUID()}`;const categoria=await gql('mutation($nombre:String!){crearCategoria(nombre:$nombre){id nombre productosCount}}',{nombre:nombreCategoria},{admin:true});
await gql('mutation($id:Int!,$nombre:String!){actualizarCategoria(id:$id,nombre:$nombre){id nombre}}',{id:categoria.crearCategoria.id,nombre:`${nombreCategoria} Editada`},{admin:true});
await gql('mutation($id:Int!){eliminarCategoria(id:$id)}',{id:categoria.crearCategoria.id},{admin:true});
await gql('mutation($id:Int!){eliminarProducto(id:$id)}',{id},{admin:true});await assert.rejects(leer,/disponible/);
const {pedidos}=await gql('{pedidos{id total detalles{nombreProducto precioUnitario producto{id}}}}',{},auth);const guardado=pedidos.find(p=>p.id===primero.id);assert.equal(guardado.total,39.8);assert.equal(guardado.detalles[0].precioUnitario,19.9);assert.equal(guardado.detalles[0].nombreProducto,datos.nombre);
assert.equal((await gql('{pedidos{id}}',{},otraAuth)).pedidos.length,0,'Una cuenta no debe ver los pedidos de otra.');
const {productos}=await gql('{productos(limite:1,desde:1){total items{id}}}');assert.equal(productos.items.length,1);
await assert.rejects(()=>gql('{productos(limite:101){total}}'),/Paginación/);
console.log('OK: autenticación, autorización admin, compras, movimientos y ajustes de inventario, cancelación, dashboard, clientes, pagos de solo lectura, categorías, CRUD de productos, paginación e historial.');
console.log('La prueba deja dos pedidos de TEST y un producto TEST dado de baja para conservar las relaciones.');
